title: 三國演義 - 吳淡如
description: 三國演義 - 吳淡如
time: Thu, 29 Aug 2024 08:22:50 +0000
items:
  - title: 00.  前言-成在智慧與勇氣 敗在昏昧與猶豫
    size: 22205348
    duration: 1387
  - title: 01.  壹-亂世出英雄（上）
    size: 25472368
    duration: 1591
  - title: 02.  壹-亂世出英雄（下）
    size: 24976609
    duration: 1560
  - title: 03.  貳-群雄聯手討伐董卓（上）
    size: 28942689
    duration: 1808
  - title: 04.  貳-群雄聯手討伐董卓（下）
    size: 33827736
    duration: 2114
  - title: 05.  參-誰都可以挾天子以令諸侯（上）
    size: 22272067
    duration: 1391
  - title: 06.  參-誰都可以挾天子以令諸侯（下）
    size: 22147873
    duration: 1384
  - title: 07.  肆-皇帝成了曹操的棋子（上）
    size: 16435263
    duration: 1027
  - title: 08.  肆-皇帝成了曹操的棋子（下）
    size: 16712728
    duration: 1044
  - title: 09.  伍-走投無路的劉備（上）
    size: 20939161
    duration: 1306
  - title: 10.  伍-走投無路的劉備（下）
    size: 20419606
    duration: 1276
  - title: 11.  陸-第一勇士呂布的下場（上）
    size: 24671955
    duration: 1539
  - title: 12.  陸-第一勇士呂布的下場（下）
    size: 28089997
    duration: 1755
  - title: 13.  柒-影子皇帝的血書（上）
    size: 29391968
    duration: 1834
  - title: 14.  柒-影子皇帝的血書（下）
    size: 28793836
    duration: 1799
  - title: 15.  捌-過五關斬六將（上）
    size: 34693508
    duration: 1443
  - title: 16.  捌-過五關斬六將（下）
    size: 33661805
    duration: 1402
  - title: 17.  玖-盟主袁紹的悲歌（上）
    size: 27448040
    duration: 1713
  - title: 18.  玖-盟主袁紹的悲歌（下）
    size: 27370267
    duration: 1710
  - title: 19.  拾-袁氏兄弟一敗塗地（上）
    size: 25585614
    duration: 1596
  - title: 20.  拾-袁氏兄弟一敗塗地（下）
    size: 25420907
    duration: 1588
  - title: 21.  拾壹-孔明初試啼聲（上）
    size: 25540892
    duration: 1593
  - title: 22.  拾壹-孔明初試啼聲（下）
    size: 26293186
    duration: 1643
  - title: 23.  拾貳-劉備帶百姓逃難（上）
    size: 22231909
    duration: 1387
  - title: 24.  拾貳-劉備帶百姓逃難（下）
    size: 22080578
    duration: 1379
  - title: 25.  拾參-瑜亮情結下的赤壁之戰（上）
    size: 27185561
    duration: 1696
  - title: 26.  拾參-瑜亮情結下的赤壁之戰（下）
    size: 26854513
    duration: 1678
  - title: 27.  拾肆-既生瑜 何生亮（上）
    size: 28072053
    duration: 1752
  - title: 28.  拾肆-既生瑜 何生亮（下）
    size: 28114236
    duration: 1756
  - title: 29.  拾伍-賠了夫人又折兵（上）
    size: 22836696
    duration: 1424
  - title: 30.  拾伍-賠了夫人又折兵（下）
    size: 23054840
    duration: 1440
  - title: 31.  拾陸-西羌英雄馬超現身（上）
    size: 21323266
    duration: 1330
  - title: 32.  拾陸-西羌英雄馬超現身（下）
    size: 20921579
    duration: 1307
  - title: 33.  拾柒-龐統命喪落鳳坡（上）
    size: 18851455
    duration: 1175
  - title: 34.  拾柒-龐統命喪落鳳坡（下）
    size: 18707647
    duration: 1169
  - title: 35.  拾捌-劉備收服馬超（上）
    size: 29064288
    duration: 1814
  - title: 36.  拾捌-劉備收服馬超（下）
    size: 29990924
    duration: 2141
  - title: 37.  拾玖-趙子龍一身是膽（上）
    size: 33880014
    duration: 2115
  - title: 38.  拾玖-趙子龍一身是膽（下）
    size: 34838364
    duration: 2177
  - title: 39.  貳拾-江山終於易主（上）
    size: 19876709
    duration: 1239
  - title: 40.  貳拾-江山終於易主（下）
    size: 20467671
    duration: 1279
  - title: 41.  貳拾壹-長江後浪推前浪（上）
    size: 18792105
    duration: 1172
  - title: 42.  貳拾壹-長江後浪推前浪（下）
    size: 18648717
    duration: 1165
  - title: 43.  貳拾貳-七擒孟獲（上）
    size: 20104079
    duration: 1254
  - title: 44.  貳拾貳-七擒孟獲（下）
    size: 17137370
    duration: 1070
  - title: 45.  貳拾參-司馬懿崛起（上）
    size: 17773148
    duration: 1110
  - title: 46.  貳拾參-司馬懿崛起（下）
    size: 17856680
    duration: 1115
  - title: 47.  貳拾肆-孔明與司馬懿的軍師傳奇（上）
    size: 13544249
    duration: 846
  - title: 48.  貳拾肆-孔明與司馬懿的軍師傳奇（下）
    size: 22107337
    duration: 1381
  - title: 49.  貳拾伍-出師未捷身先死（上）
    size: 23942648
    duration: 1496
  - title: 50.  貳拾伍-出師未捷身先死（下）
    size: 27235305
    duration: 1702
  - title: 51.  貳拾陸-姜維對敵司馬昭（上）
    size: 11638765
    duration: 727
  - title: 52.  貳拾陸-姜維對敵司馬昭（下）
    size: 10616377
    duration: 663
  - title: 53.  貳拾柒-三國一統（上）
    size: 13574746
    duration: 848
  - title: 54.  貳拾柒-三國一統（下）
    size: 12800626
    duration: 799
